import React from "react";
import FooterIcon from "../Icons/FooterIcon";
import s from "./Footer.module.scss";

const Footer = () => {
  return (
    <div className={s.footer}>
      <span className={s.footerLabel}>Messages are generated by AI. Some responses may be inaccurate.</span>
    </div>
  )
}

export default Footer;
